### PR TITLE
Clean gemspec/gemfile and add preliminary PrawnPDF formatter test suite

### LINKED ISSUE #23: Dependency on pdf-writer requires out-of-date hoe/rake
From @Nitrodist on #22:

@Odaeus with 1.6.3, ruport has a dependency on pdf-writer, which has a dependency on transaction-simple, which has a dependency on hoe, which has a runtime dependency on rake. @jherdman fixed it by updating hoe manually to a fixed hoe version. 

How about a new release of ruport? The stuff in 1.6.3 is a little over 2 years old.

Below is the dependency chain:

```
vagrant@debian-squeeze64:/vagrant$ bundle exec gem dependency ruport
Gem ruport-1.6.3
  fastercsv (>= 0)
  pdf-writer (= 1.1.8)

Gem ruport-util-0.14.0
  mailfactory (>= 1.2.3)
  rubyzip (>= 0.9.1)
  ruport (>= 1.6.0)

vagrant@debian-squeeze64:/vagrant$ bundle exec gem dependency pdf-writer
Gem pdf-writer-1.1.8
  color (>= 1.4.0)
  transaction-simple (~> 1.3)

vagrant@debian-squeeze64:/vagrant$ bundle exec gem dependency transaction-simple
Gem transaction-simple-1.4.0
  hoe (>= 1.1.7)

vagrant@debian-squeeze64:/vagrant$ bundle exec gem dependency hoe
Gem hoe-2.12.3
  minitest (~> 2.5, development)
  rake (~> 0.8)
```

### LINKED ISSUE #50: Cleanup the gemspec
- remove the conditional
- review all the rest

### PR DESCRIPTION
**Pull request by saveriomiroddi**
- remove support for ancient rubygems version (1.2.0, from 2008)
- remove rake gem requirement in the Gemfile, since it's already in the gemfile
- remove the pdf-writer dependency, since the PDF formatter is gone
- downgrade Prawn version, until the test suite is fully restored
- add preliminary PrawnPDF formatter test suite

Closes #50; closes #23.

### CODE REVIEW

**Comment by saveriomiroddi** [comment]
@Odaeus Work in progress, I'm manually testing the PDF writing. the website content is unfortunately very old :scream:

**Comment by saveriomiroddi** [comment]
@Odaeus so! I've done a bit of work with the gemspec and the test suite. there was no test suite for prawn pdf rendering, so I've started a preliminary test suite.
The prawn dependency needs to stay unfortunately to the previous, very old, version 0.12.0 :sob: I will slowly extend the test suite to have reasonable coverage, then I'll have a look again.

**Comment by saveriomiroddi** [comment]
@Odaeus ok, I've removed the PrawnPDF formatter "placeholder" unit tests (the broken ones; there are a few working ones, and the new smoke test with real PDF data), so this PR is ready.

I've moved the broken ones into a separate branch; I'll repair them, and create a separate PR.

**Comment by kbrock** [comment]
kicking it to run again.

in prep of merging

**Comment by kbrock** [comment]
Thanks for the great change @saveriomiroddi 
Sorry for the delay

**Pull request merged**
