### PR TITLE
Update to prawn 2.4.0, which added ruby 3 support.

### PR DESCRIPTION
**Pull request by jrafanie**
See: https://github.com/prawnpdf/prawn/blob/2.4.0/CHANGELOG.md

### CODE REVIEW

**Comment by kbrock** [comment]
the only breaking change was dropping outdated ruby versions. LGTM

**Comment by kbrock** [comment]
CI is broken. but test ran locally for me:

```
bundle exec rake # 🍺 🍺
/Users/kbrock/.rubies/ruby-2.7.1/bin/ruby -w -I"lib:test" /Users/kbrock/.gem/ruby/2.7.1/gems/rake-13.0.6/lib/rake/rake_test_loader.rb "test/table_pivot_test.rb" "test/markdown_formatter_test.rb" "test/grouping_test.rb" "test/prawn_pdf_formatter_test.rb" "test/html_formatter_test.rb" "test/data_feeder_test.rb" "test/controller_test.rb" "test/text_formatter_test.rb" "test/template_test.rb" "test/record_test.rb" "test/table_test.rb" "test/csv_formatter_test.rb"
Run options: --seed 11782

# Running:

............................../Users/kbrock/.gem/ruby/2.7.1/gems/prawn-table-0.2.2/lib/prawn/table.rb:431: warning: instance variable @header_row not initialized
/Users/kbrock/.gem/ruby/2.7.1/gems/prawn-table-0.2.2/lib/prawn/table.rb:431: warning: instance variable @header_row not initialized
/Users/kbrock/.gem/ruby/2.7.1/gems/prawn-table-0.2.2/lib/prawn/table.rb:431: warning: instance variable @header_row not initialized
..............................................................................................................................................................................................................................

Finished in 1.526131s, 165.1234 runs/s, 425.2584 assertions/s.

252 runs, 649 assertions, 0 failures, 0 errors, 0 skips
[Coveralls] Outside the CI environment, not sending data.
```

**Comment by kbrock** [comment]
ok, reindented the diff results. Talk about subtle differences

Even after seeing the differences, still not sure if we care

```
diff before.txt after.tt
```

```diff
117,123c117,122
< 54, 49, 50, 46, 48, 32, 55, 57, 50, 46, 48, 93, 10, 47, 67, 114, 111, 112, 66,
< 111, 120, 32, 91, 48, 32, 48, 32, 54, 49, 50, 46, 48, 32, 55, 57, 50, 46, 48,
< 93, 10, 47, 66, 108, 101, 101, 100, 66, 111, 120, 32, 91, 48, 32, 48, 32, 54,
< 49, 50, 46, 48, 32, 55, 57, 50, 46, 48, 93, 10, 47, 84, 114, 105, 109, 66, 111,
< 120, 32, 91, 48, 32, 48, 32, 54, 49, 50, 46, 48, 32, 55, 57, 50, 46, 48, 93,
< 10, 47, 65, 114, 116, 66, 111, 120, 32, 91, 48, 32, 48, 32, 54, 49, 50, 46, 48,
< 32, 55, 57, 50, 46, 48, 93, 10, 47, 67, 111, 110, 116, 101, 110, 116, 115, 32,
---
> 54, 49, 50, 32, 55, 57, 50, 93, 10, 47, 67, 114, 111, 112, 66, 111, 120, 32,
> 91, 48, 32, 48, 32, 54, 49, 50, 32, 55, 57, 50, 93, 10, 47, 66, 108, 101, 101,
> 100, 66, 111, 120, 32, 91, 48, 32, 48, 32, 54, 49, 50, 32, 55, 57, 50, 93, 10,
> 47, 84, 114, 105, 109, 66, 111, 120, 32, 91, 48, 32, 48, 32, 54, 49, 50, 32,
> 55, 57, 50, 93, 10, 47, 65, 114, 116, 66, 111, 120, 32, 91, 48, 32, 48, 32, 54,
> 49, 50, 32, 55, 57, 50, 93, 10, 47, 67, 111, 110, 116, 101, 110, 116, 115, 32,
142c141
< 10, 48, 48, 48, 48, 48, 48, 50, 52, 52, 55, 32, 48, 48, 48, 48, 48, 32, 110,
---
> 10, 48, 48, 48, 48, 48, 48, 50, 52, 50, 55, 32, 48, 48, 48, 48, 48, 32, 110,
146c145
< 120, 114, 101, 102, 10, 50, 53, 52, 52, 10, 37, 37, 69, 79, 70, 10]
---
> 120, 114, 101, 102, 10, 50, 53, 50, 52, 10, 37, 37, 69, 79, 70, 10]
```

**Comment by kbrock** [comment]
Wonder if it makes sense to render these to text files and visually determine if they are close enough.

**Comment by jrafanie** [comment]
@kbrock what do you think we should do here?  Shall I try to figure out if these test changes are ok with ruby 3 and newer prawn?

**Comment by kbrock** [comment]
@jrafanie I didn't look too far into this, just saved the diff to a text file.

Not sure how to save this to a pdf file. But if you know how to do that we can just double click the output files and see if the results are close enough.

Pdf has a way of having different values but the end result is close enough.

**Pull request merged**
