### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by kbrock**
Hello,

Tests have not passed since the `thead` code was added.

- This fixes those tests
- This respects `show_table_headers` for groupings.
- It also adds travis for testing recent versions of ruby

### CODE REVIEW

**Comment by kbrock** [comment]
@Odaeus Ruby 2.0 was getting confused between `::CSV` and `Formatter::CSV`. 

I notice that you removed 1.8.7 from travis. Since `faster_csv` was only used for 1.8.7, I removed it.
If you would prefer to leave 1.8.7 support unofficially in there, let me know and I can fix ruby 2.0 support while leaving fastercsv in there.

Thanks for this project
-Keenan

**Comment by kbrock** [comment]
@Odaeus would you merge this to fix the tests?

**Comment by Odaeus** [comment]
Than you for this, and sorry for letting it languish.

There were a couple of issues:
* The tests were order dependent as the `table_test.rb` file failed by itself if CSV hadn't been required elsewhere beforehand.
* The logic and method for the table/group headings was quite right.

I've fixed those issues by cherry-picking your commits and amending them, you are still attributed as the author. I hope that's satisfactory. Thanks again!

**Comment by kbrock** [comment]
thanks @Odaeus - just wanted to help

**Pull request closed without merging**
