### PR TITLE
Add the current supported Ruby version to Travis

### PR DESCRIPTION
**Pull request by saveriomiroddi**
Add Ruby versions 2.3 to 2.5, and allow ruby-head to fail.

This PR also removes the PDF formatter, since it works only on Ruby 1.8, which is long unsupported by Ruport.

### CODE REVIEW

**Comment by Odaeus** [comment]
Happy to remove the PDF formatter but please keep as many Ruby 2.x versions as possible because they really aren't that old even if official support has been stopped.

**Comment by saveriomiroddi** [comment]
@Odaeus restored 2.0 and 2.1.

**Comment by saveriomiroddi** [comment]
I'll also take care of the failure, and ping you back.

**Comment by saveriomiroddi** [comment]
There is a significant change to review, let me post it.

**Comment by saveriomiroddi** [comment]
This:

    diff --git a/lib/ruport/controller.rb b/lib/ruport/controller.rb
    index fd6717a..b6f598e 100644
    --- a/lib/ruport/controller.rb
    +++ b/lib/ruport/controller.rb
    @@ -216,7 +216,7 @@ class Ruport::Controller
         def built_in_formats
          { :html => Ruport::Formatter::HTML,
            :csv  => Ruport::Formatter::CSV,
    -       :pdf  => Ruport::Formatter::PDF,
    +       :pdf  => Ruport::Formatter::PrawnPDF,
            :prawn_pdf => Ruport::Formatter::PrawnPDF,
            :text => Ruport::Formatter::Text }
         end

I've redirected the old `:pdf` renderer symbol to Prawn.

There are a two options, up to your decision:

- entirely discard the `:pdf` 
- redirect it to Prawn (like I've done)

I think both are valid. If you prefer option 1, let me know!

**Comment by saveriomiroddi** [comment]
@Odaeus can you confirm the `:pdf` redirection? sorry for asking it, but since it's related to the removal, I wanted to be completely sure this won't hurt the code!

**Comment by Odaeus** [comment]
@saveriomiroddi sorry! Yes I saw that and it makes complete sense to switch the formatter. I think it'll need a major version bump when released though.

**Comment by saveriomiroddi** [comment]
@Odaeus super. I've created a milestone with the PRs/issues. I've called it `1.8.0`, but you can change it to anything you want (if you want to update the major version, it would be `2.0.0` according to semantic versioning).

**Pull request merged**
